### PR TITLE
Property API - Update Swagger doc

### PR DESCRIPTION
**Pull request by a-jomills**
Summary:
This PR updates the Try It page to update the static swagger doc.

### CODE REVIEW

**Comment by JoshExpedia** [comment]
Hey - you need credentials to access the link you specified (https://services.expediapartnercentral.com/properties/v1/docs/v1/swagger)

As such the try it page fails to load swagger (live example of this branch): http://swaggerdoc-propertyapi.partner-api-preview.test.expedia.com/apis/product-management/property-api/try-it.html

**Comment by a-jomills** [comment]
[Implement Swagger Docs by Q1 2017 Hackathon](https://trello.com/c/r9ghR29j/133-implement-swagger-docs-by-q1-2017-hackathon)

**Comment by a-jomills** [comment]
Yea, I figured that it might creds. @JoshExpedia Is there any way to inject them?
I have the static file working in prod now.

**Comment by JoshExpedia** [comment]
I dont think so - the solution is probably to remove credential requirements from swagger for either just that path or the whole thing (because, well, if credentials are sent through the browser so that the user can access without ever logging in, what's the point of having the credentials?)

**Comment by JoshExpedia** [comment]
I'll merge this now?

**Comment by a-jomills** [comment]
No, It's still under review, and we have to wait for another team to update Apigee so we get the endpoint exposed w/o BasicAuthN.
I'm taking the opportunity to test the docs with examples built-in.

**Comment by a-jomills** [comment]
**DON'T MERGE YET!!**

Testing INT

**Pull request merged**
